### PR TITLE
feat: create map styles

### LINKED ISSUE #7: further map refinements
### Context

follows #5 

By making the map display as simple as possible, we will have a better starting point for doing fancier stuff

### Requirements

- make the default map style simpler:
   - just draws outlines for states, then counties and maybe municipalities the further you zoom in. 
      - https://docs.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/
      - https://www.census.gov/geographies/mapping-files/time-series/geo/cartographic-boundary.html
   - No roads, just place labels, and black/white.
- use lat/lng from the API (https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/240)

### PR DESCRIPTION
**Pull request by joshuagraber**
Resolves #7 

Add Mapbox themes for light and dark mode.
Add font awesome icon and theme

To test:
1. Run `npm run dev`
2. Navigate to `localhost:8888` and ensure the map styles display as expected (switch light/dark preference, zoom in and out, etc.)

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
This is looking good! However, I don't think I'm getting county layers, and I feel like there's more detail showing than the screenshots you sent earlier in the process. 

Screen Shot 2024-04-09 at 1 08 38 PM

**Comment by joshuagraber** [comment]
> However, I don't think I'm getting county layers, and I feel like there's more detail showing than the screenshots you sent earlier in the process.

@josh-chamberlain This is what I'm seeing locally in light mode, which seems to be showing the county boundaries and land mass details removed from the map as we discussed. Maybe something is in cache?

Screenshot 2024-04-09 at 1 33 00 PM

Also, the API is returning `500` from `pdap.io` on all endpoints right now (already pinged @mbodeantor) , so I'm running this locally for the time being.
(Run data sources, uncomment lines 13-14 in `src/components/DataSourceMap.vue`, comment out lines 11-12)

**Comment by josh-chamberlain** [comment]
@joshuagraber yep, cache issue...thanks. It's looking good. Is most of the visual config done in mapbox?

1. What do you think about having a layer of map icons for agencies without any sources, set to 20% opacity? That way there would be little gray icons showing what we don't yet have. Could be too scary.

2. What do you think about a little box which shows the agencies that appear on the map, in list form? Clicking them would take you to a search with the appropriate filter for agency, or if you clicked the county you'd get everything from the county. If there are cases with too many agencies, we could truncate to "...and 117 more agencies"

Screen Shot 2024-04-10 at 12 54 49 PM

**Review by josh-chamberlain — APPROVED** [review]
looks good, up to you if you want to do any of my suggested changes on this branch or a new one

**Comment by joshuagraber** [comment]
Hey @josh-chamberlain Sounds good, I'll give all of those suggestions a go. I do think it's another step in the work, so I'll create an issue and begin working in a new branch tomorrow. Ty!

**Pull request merged**
